# Generated by Django 6.0.7 on 2026-08-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('leadership', 'Leadership'), ('board', 'Board of Directors'), ('advisor', 'Chief Advisor'), ('technical', 'Technical Team'), ('corporate', 'Corporate Support')], default='technical', max_length=20),
        ),
    ]
