# Generated by Django 6.0.7 on 2026-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage_alter_teammember_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
