# Generated by Django 6.0.7 on 2026-08-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_contactmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('leadership', 'Leadership'), ('board', 'Board of Directors'), ('advisor', 'Advisors'), ('technical', 'Technical Team'), ('corporate', 'Corporate Support')], default='technical', max_length=20),
        ),
    ]
